-- Seed 30 Guest-Focused Prompts
INSERT INTO public.prompt_library_global (title, prompt_text, tags) VALUES
-- Friends & Family
('First Impression', 'What was your very first impression of me? Be honest!', ARRAY['guest', 'friend', 'fun']),
('Favorite Memory', 'What is your absolute favorite memory of us together?', ARRAY['guest', 'friend', 'love']),
('Hidden Talent', 'What is a talent or skill I have that you think I underestimate?', ARRAY['guest', 'friend', 'praise']),
('Proudest Moment', 'When were you most proud of me?', ARRAY['guest', 'family', 'love']),
('Funny Story', 'Tell the story of the time we laughed the hardest.', ARRAY['guest', 'friend', 'fun']),
('Wisdom', 'What is the one piece of advice I gave you that stuck?', ARRAY['guest', 'wisdom']),
('Childhood', 'What was I like as a child? (If you knew me then!)', ARRAY['guest', 'family', 'childhood']),
('School Days', 'What is a memory from our school days that defines our friendship?', ARRAY['guest', 'friend', 'history']),
('Adventure', 'What was the craziest adventure we went on?', ARRAY['guest', 'friend', 'adventure']),
('Support', 'Describe a time I was there for you when you needed it most.', ARRAY['guest', 'friend', 'deep']),
('First Date', 'If you are my partner: What do you remember most about our first date?', ARRAY['guest', 'love', 'romance']),
('Wedding Day', 'What is your favorite moment from our wedding?', ARRAY['guest', 'love', 'romance']),
('Parenting', 'What do you think is my greatest strength as a parent?', ARRAY['guest', 'family', 'parenting']),
('Siblings', 'What is the most annoying thing I did as a sibling? (And the best?)', ARRAY['guest', 'family', 'fun']),
('Traditions', 'What family tradition do you hope we keep forever?', ARRAY['guest', 'family', 'culture']),
('Cooking', 'What is the best meal I ever cooked for you? (Or the worst!)', ARRAY['guest', 'friend', 'food']),
('Travel', 'What was our best trip together and why?', ARRAY['guest', 'adventure']),
('Change', 'How have you seen me change or grow over the years?', ARRAY['guest', 'deep', 'reflection']),
('Descriptive Word', 'If you had to describe me in one word, what would it be and why?', ARRAY['guest', 'short']),
('Surprise', 'What is something I did that completely surprised you?', ARRAY['guest', 'fun']),
('Gift', 'What is the best gift I ever gave you?', ARRAY['guest', 'love']),
('Challenge', 'What is a challenge we overcame together?', ARRAY['guest', 'deep']),
('Bucket List', 'What is one thing you still want us to do together?', ARRAY['guest', 'future']),
('Legacy', 'What do you think is the mark I leave on the people around me?', ARRAY['guest', 'deep', 'legacy']),
('Work', 'What is it like working with me? (If applicable)', ARRAY['guest', 'career']),
('College', 'What is a classic "college" story about me?', ARRAY['guest', 'school', 'fun']),
('Holidays', 'What is your favorite holiday memory with me?', ARRAY['guest', 'family', 'holiday']),
('Comfort', 'How do I make you feel when we are together?', ARRAY['guest', 'deep', 'love']),
('Future', 'Where do you see us in 10 years?', ARRAY['guest', 'future']),
('Gratitude', 'What is something about our relationship you are grateful for?', ARRAY['guest', 'love']);

-- Seed 30 User-Focused Prompts
INSERT INTO public.prompt_library_global (title, prompt_text, tags) VALUES
-- User Reflection
('Morning Ritual', 'Describe your perfect morning. What happens?', ARRAY['user', 'lifestyle']),
('Night Ritual', 'How do you unwind at the end of a long day?', ARRAY['user', 'lifestyle']),
('First Job', 'What was your very first job? What did you learn?', ARRAY['user', 'career']),
('Mentor', 'Who was the most influential mentor in your life?', ARRAY['user', 'career', 'wisdom']),
('Failure', 'Talk about a failure that actually taught you something valuable.', ARRAY['user', 'growth', 'career']),
('Book', 'What is a book that changed your perspective on life?', ARRAY['user', 'wisdom', 'culture']),
('Song', 'What song instantly takes you back to a specific moment? Which moment?', ARRAY['user', 'music', 'memory']),
('Fear', 'What was a fear you conquered?', ARRAY['user', 'growth']),
('Risk', 'What is the biggest risk you ever took? Was it worth it?', ARRAY['user', 'growth']),
('Kindness', 'Describe a random act of kindness you received.', ARRAY['user', 'love']),
('Home', 'What does "home" mean to you?', ARRAY['user', 'deep']),
('Nature', 'Where in nature do you feel most at peace?', ARRAY['user', 'nature']),
('Skill', 'What is a skill you are currently trying to learn?', ARRAY['user', 'growth']),
('Lost Item', 'Have you ever lost something you loved? What was it?', ARRAY['user', 'memory']),
('Pet', 'Tell a story about a beloved pet from your past.', ARRAY['user', 'memory', 'family']),
('Recipe', 'What is a family recipe you want to pass down?', ARRAY['user', 'food', 'legacy']),
('Historical Event', 'What is a major historical event you lived through? What was it like?', ARRAY['user', 'history']),
('Technology', 'How has technology changed your life since you were a kid?', ARRAY['user', 'reflection']),
('Advice to Younger Self', 'What would you tell your 20-year-old self?', ARRAY['user', 'wisdom', 'legacy']),
('Hobby', 'What is a hobby that gives you joy?', ARRAY['user', 'lifestyle']),
('Season', 'What is your favorite season and why?', ARRAY['user', 'nature']),
('City', 'What is your favorite city you have visited?', ARRAY['user', 'travel']),
('Dream', 'What is a recurring dream or a dream you remember vividly?', ARRAY['user', 'deep']),
('Superpower', 'If you could have one superpower, what would it be?', ARRAY['user', 'fun']),
('Possession', 'What is your most prized material possession?', ARRAY['user', 'lifestyle']),
('Forgiveness', 'Is there someone you need to forgive? Or ask forgiveness from?', ARRAY['user', 'deep']),
('Belief', 'What is a core belief you hold that guides your life?', ARRAY['user', 'wisdom']),
('Secret', 'What is a small secret you are willing to share now?', ARRAY['user', 'fun']),
('Turning Point', 'What was a major turning point in your life?', ARRAY['user', 'deep', 'growth']),
('Legacy Wish', 'How do you want to be remembered?', ARRAY['user', 'legacy']);
